### PR TITLE
Validation fail response listener, docs for response listener

### LINKED ISSUE #2: Add response listeners
Make sure they are only active on some endpoints. Also make sure they respond with fractal stuff

### PR DESCRIPTION
**Pull request by aradoje**
This will fix #2

### CODE REVIEW

File: EventListener/ExceptionListener.php [hunk 1]
```diff
@@ -62,13 +61,7 @@ public function onKernelException(GetResponseForExceptionEvent $event)
         } elseif ($exception instanceof NotFoundHttpException) {
             $response = $this->responseFactory->createNotFound();
         } elseif ($exception instanceof ValidationFailedException) {
-            $message = '';
-            /** @var ConstraintViolationInterface $violation */
-            foreach ($exception->getViolations() as $violation) {
```
Comment (Nyholm) [inline EventListener/ExceptionListener.php:67]: Isn't this a more nice way of displaying the errors?

File: Readme.md [hunk 2]
```diff
@@ -60,3 +60,15 @@ security:
             wsse:      true
 
 ```
+
+## Exception listener
+
+Exception listener is enabled by default. It will catch uncaught exceptions and return formatted json response.
+
+To disable/configure it, in config.yml add
```
Comment (Nyholm) [inline Readme.md]: "Here is an example configuration:"

**Review by Nyholm — CHANGES_REQUESTED** [review]
Thank you. Just some comments though

File: EventListener/ExceptionListener.php (hunk 1 above)
Comment (aradoje) [reply EventListener/ExceptionListener.php:67]: We have response in `ResponseFactory` (https://github.com/Happyr/ApiBundle/blob/master/Service/ResponseFactory.php#L223) 
that parses the `ConstraintViolationList` into nice json response, which is more convenient than string message i think. What do you think?

Comment (Nyholm) [reply EventListener/ExceptionListener.php:67]: oh, I did not know. You are correct.

**Review by Nyholm — APPROVED** [review]
Excellent. Thank you
